# tmux-powerline configuration
# Tomorrow Light edition

# General
export TMUX_POWERLINE_DEBUG_MODE_ENABLED="false"
export TMUX_POWERLINE_ERROR_LOGS_ENABLED="false"
export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"

# Theme
export TMUX_POWERLINE_THEME="tomorrow-light"
export TMUX_POWERLINE_DIR_USER_THEMES="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/themes"
export TMUX_POWERLINE_DIR_USER_SEGMENTS="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/segments"

# Status bar
export TMUX_POWERLINE_STATUS_VISIBILITY="on"
export TMUX_POWERLINE_STATUS_INTERVAL="5"
export TMUX_POWERLINE_STATUS_JUSTIFICATION="centre"
export TMUX_POWERLINE_STATUS_LEFT_LENGTH="100"
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="120"
export TMUX_POWERLINE_WINDOW_STATUS_SEPARATOR=""

# Mute keybindings
export TMUX_POWERLINE_MUTE_LEFT_KEYBINDING="C-["
export TMUX_POWERLINE_MUTE_RIGHT_KEYBINDING="C-]"

# -- Segment settings -------------------------------------------------------

# battery.sh
export TMUX_POWERLINE_SEG_BATTERY_TYPE="percentage"

# date.sh
export TMUX_POWERLINE_SEG_DATE_FORMAT="%b %d"

# time.sh
export TMUX_POWERLINE_SEG_TIME_FORMAT="%H:%M"

# now_playing.sh
export TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER="spotify"
export TMUX_POWERLINE_SEG_NOW_PLAYING_MAX_LEN="30"
export TMUX_POWERLINE_SEG_NOW_PLAYING_TRIM_METHOD="trim"
export TMUX_POWERLINE_SEG_NOW_PLAYING_NOTE_CHAR="♫"
export TMUX_POWERLINE_SEG_NOW_PLAYING_NOT_PLAYING=""

# pwd.sh
export TMUX_POWERLINE_SEG_PWD_MAX_LEN="30"

# tmux_session_info.sh
export TMUX_POWERLINE_SEG_TMUX_SESSION_INFO_FORMAT="#S:#W"

# tmux_continuum_status.sh
export TMUX_POWERLINE_SEG_TMUX_CONTINUUM_PATH="$HOME/.tmux/plugins/tmux-continuum"
export TMUX_POWERLINE_SEG_TMUX_CONTINUUM_PREFIX=""

# vcs_branch.sh
export TMUX_POWERLINE_SEG_VCS_BRANCH_MAX_LEN="30"

# weather.sh
export TMUX_POWERLINE_SEG_WEATHER_DATA_PROVIDER="yrno"
export TMUX_POWERLINE_SEG_WEATHER_UNIT="f"
export TMUX_POWERLINE_SEG_WEATHER_UPDATE_PERIOD="600"
export TMUX_POWERLINE_SEG_WEATHER_LAT="auto"
export TMUX_POWERLINE_SEG_WEATHER_LON="auto"

# kubernetes_context.sh
export TMUX_POWERLINE_SEG_KUBERNETES_CONTEXT_DISPLAY_MODE="name"
export TMUX_POWERLINE_SEG_KUBERNETES_CONTEXT_SYMBOL="󱃾"
export TMUX_POWERLINE_SEG_KUBERNETES_CONTEXT_SYMBOL_COLOUR="239"

# vpn.sh
export TMUX_POWERLINE_SEG_VPN_DISPLAY_MODE="name"
export TMUX_POWERLINE_SEG_VPN_SYMBOL="󱠾 "
export TMUX_POWERLINE_SEG_VPN_SYMBOL_COLOUR="239"

# hostname.sh
export TMUX_POWERLINE_SEG_HOSTNAME_FORMAT="short"

# mode_indicator.sh
export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_AND_PREFIX_MODE_ENABLED="true"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_MOUSE_MODE_ENABLED="false"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_ENABLED="true"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_MODE_TEXT="NORMAL"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_PREFIX_MODE_TEXT="PREFIX"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_TEXT="COPY"
