(use-package all-the-icons
  ;;:brushup
  ;;(defun brushup-all-the-icons ()
    ;;(setq brushup-icons brushup-fg-1)
    ;;(set-face-attribute 'all-the-icons-blue nil :height 0.8 :foreground brushup-bg :background brushup-bg)
    ;;;; used as default icon face
    ;;(set-face-attribute 'all-the-icons-lred nil :height 0.8 :foreground brushup-icons)
    ;;;; used as unfocused icon face
    ;;(set-face-attribute 'all-the-icons-blue-alt nil :height 0.8 :foreground brushup-bg-2)
    ;;(set-face-attribute 'all-the-icons-dpurple nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-purple nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lpurple nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-cyan nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-cyan-alt nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dblue nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dcyan nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dgreen nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dmaroon nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dorange nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dpink nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dred nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dsilver nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-dyellow nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-green nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lblue nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lcyan nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lgreen nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lmaroon nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lorange nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lpink nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lsilver nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-lyellow nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-maroon nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-orange nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-pink nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-purple nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-purple-alt nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-red nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-red-alt nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-silver nil :height 0.8 :foreground brushup-icons)
    ;;(set-face-attribute 'all-the-icons-yellow nil :height 0.8 :foreground brushup-icons)
    ;;)
  ;;(add-to-list 'brushup-styles '(brushup-all-the-icons))

  ;;:hook (use-package--all-the-icons--post-config . z-brushup)
  )
