(use-package ace-window)
(use-package adaptive-wrap)
(use-package ag)
(use-package alert)
(use-package all-the-icons)
(use-package all-the-icons-dired)
(use-package all-the-icons-ibuffer)
(use-package avy)
(use-package bash-completion)
(use-package biblio)
(use-package blacken)
(use-package bookmark)
(use-package bookmark+)
(use-package bookmark-in-project)
(use-package bookmark-view)
(use-package browse-url)
(use-package bufler)
(use-package cape)
(use-package cheat-sh)
(use-package chocolate-theme)
(use-package citar)
(use-package citar-embark)
(use-package citar-org-roam)
(use-package color)
(use-package consult)
(use-package consult-dir)
(use-package consult-lsp)
(use-package consult-org-roam)
(use-package consult-yasnippet :after (consult yasnippet))
;; todo: special way to load 'my' repos
(use-package convention :straight nil :load-path "~/.files/.zetta.d/source/zettapkg/convention" :demand t)
(use-package csv-mode)
(use-package dabbrev)
(use-package dap-mode)
(use-package dash)
(use-package dash-docs)
(use-package dash-functional)
(use-package default-text-scale)
(use-package define-word)
(use-package desktop)
;;(use-package detached)
(use-package dimmer)
(use-package dired :straight (:type built-in))
(use-package dired-ranger)
(use-package dired-subtree)
(use-package display-fill-column-indicator)
(use-package display-line-numbers)
(use-package docker)
(use-package docker-compose-mode)
;;(use-package docker-tramp)
(use-package dockerfile-mode)
(use-package dogears)
(use-package dumb-jump)

;; todo factor this into a separate file, especially since it's more
;; of a QT sidecar to emacs as opposed to emacs / elisp itself.  This
;; also makes the use package declaration huge!
;;(use-package eaf
  ;;:straight
  ;;(eaf :type git :host github :repo "emacs-eaf/emacs-application-framework"           
       ;;:files ("*.el" "*.py" "core" "app" "*.json")
       ;;:includes (eaf-pdf-viewer eaf-browser eaf-image-viewer eaf-terminal
                                 ;;eaf-org-previewer eaf-markdown-previewer)
       ;;:pre-build ("python3" "install-eaf.py" "--install" "pdf-viewer"
                   ;;"browser" "image-viewer" "terminal" "org-previewer"
                   ;;"markdown-previewer" "--ignore-sys-deps")))

;;(use-package eaf-browser)
;;(use-package eaf-image-viewer)
;;(use-package eaf-markdown-previewer)
;;(use-package eaf-org-previewer)
;;(use-package eaf-pdf-viewer)
(use-package ein)
(use-package elfeed)
(use-package elfeed-org :after (elfeed))
(use-package elfeed-score :after (elfeed))
(use-package elfeed-summary :after (elfeed))
(use-package elfeed-tube :after (elfeed))
(use-package elfeed-tube)
(use-package elisp-mode :straight (:type built-in))
(use-package embark)
(use-package embark-consult)
(use-package emmet-mode)
(use-package epresent)
(use-package evil)
(use-package evil-anzu)
(use-package evil-collection)
(use-package evil-exchange)
(use-package evil-fringe-mark)
(use-package evil-indent-plus)
(use-package evil-matchit)
(use-package evil-search-highlight-persist)
(use-package evil-surround)
(use-package eww)
(use-package expand-region)
(use-package f)
(use-package face-remap)
(use-package flycheck)
(use-package flycheck-aspell)
(use-package flycheck-indicator)
(use-package flycheck-projectile)
;;(use-package flycheck-pycheckers)
(use-package focus)
(use-package foreman :straight nil :load-path "~/.files/.zetta.d/source/zettapkg/foreman" :demand t)
(use-package forge)
(use-package general)
(use-package git-gutter)
(use-package github-theme)
(use-package grep)
(use-package helm)
(use-package helm-themes)
(use-package helm-wikipedia)
(use-package helpful)
(use-package hercules)
(use-package heroku-theme)
(use-package hide-mode-line)
(use-package highlight-indent-guides)
(use-package highlight-symbol)
(use-package highlight-symbol)
(use-package hl-line)
(use-package ht)
(use-package htmlize )
(use-package hungry-delete)
(use-package hydra)
(use-package hyperbole)
(use-package ibuffer)
(use-package iedit)
(use-package image-mode)
(use-package jbeans-theme)
(use-package js2-mode)
(use-package json-snatcher)
(use-package jsonian)
(use-package key-chord)
(use-package lavender-theme)
(use-package leuven-theme)
(use-package lin)
;;(use-package linum-relative)
(use-package lsp-mode)
(use-package lsp-treemacs)
(use-package lsp-ui)
(use-package magit)
(use-package magit-diff-flycheck)
(use-package marginalia)
(use-package markdown-mode)
(use-package mermaid-mode)
(use-package modern-fringes)
(use-package modus-themes)
(use-package mw-thesaurus)
(use-package nord-theme)
(use-package numpydoc)
(use-package ob-mermaid)
(use-package olivetti)
(use-package orderless)
(use-package org)
(use-package org-agenda :straight (:type built-in))
(use-package org-capture :straight (:type built-in))
(use-package org-modern)
;; think the order needs ot change here:
;; Debugger entered--Lisp error: (error "pdf-info-epdfinfo-program is not executable")
;; (use-package org-noter)
;; (use-package mrg-noter-pdftools)
;; (use-package org-pdftools)
(use-package org-ql)
(use-package org-ref)
(use-package org-roam)
(use-package org-roam-timestamps)
(use-package org-roam-ui)
(use-package org-super-agenda)
(use-package origami)
(use-package ov)
(use-package ox-jekyll-md)
(use-package ox-reveal)
(use-package pdf-tools)
(use-package pocket-reader)
(use-package poet-theme)
(use-package projectile)
(use-package pubmed)
(use-package py-snippets :after yasnippet)
(use-package python)
(use-package pyvenv)
(use-package rainbow-mode)
(use-package rebecca-theme)
(use-package recursion-indicator)
(use-package replace :straight (:type built-in))
(use-package rjsx-mode)
(use-package s)
(use-package savehist)
(use-package scroll-bar :straight (:type built-in))
(use-package sh-script)
(use-package shell)
(use-package smartparens)
(use-package spray)
(use-package sql)
(use-package sql-indent)
(use-package sqlup-mode)
(use-package super-save)
(use-package sx)
(use-package tab-line :straight (:type built-in))
(use-package terraform-mode)
(use-package text-mode :straight (:type built-in))
(use-package tokei)
(use-package transient)
(use-package tree-mode)
;;(use-package tree-sitter)
;;(use-package tree-sitter-langs)
(use-package treemacs)
(use-package treemacs-all-the-icons)
(use-package treemacs-magit)
(use-package treemacs-projectile)
(use-package ts)
(use-package undo-tree)
(use-package unidecode)
(use-package vc)
(use-package vertico :straight (:files (:defaults "extensions/*")))
(use-package vimish-fold)
(use-package visual-fill-column)
(use-package vterm :demand t)
(use-package web-mode)
(use-package wgrep)
(use-package which-key)
(use-package windmove)
(use-package window :straight (:type built-in))
(use-package winds)
(use-package xref)
(use-package yaml)
(use-package yaml-mode)
(use-package yaml-path)
(use-package yaml-pro)
(use-package yasnippet)
(use-package yasnippet-snippets)
(use-package zenburn-theme)
