# easier reloads
bind r source-file ~/.tmux.conf

# don't rename windows automatically
set-option -g allow-rename off

# index from 1 (this is for ergonomic reasons)
set -g base-index 1

# scrollback
set-option -g history-limit 3000

# remap prefix key
# unbind C-b
# set-option -g prefix C-x
# bind-key C-x send-prefix

# sane splits
bind h split-window -h
bind v split-window -v

unbind '"'
unbind %

# faster pane switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n S-Left  previous-window
bind -n S-Right next-window


# theme
#set -g status-bg white
#set -g status-fg black

#set -g message-style bg=green
#set -g mode-style bg=green
#set -g copy-mode-current-match-style bg=green
#set -g copy-mode-match-style bg=green
#set -g copy-mode-mark-style bg=green


# remain on exit
set-option -g remain-on-exit on

set-window-option -g aggressive-resiz
set -g display-panes-time 4000

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

setw -g mouse on

# pane name
set -g pane-border-status top
set -g pane-border-format "#{pane_title}"

# https://github.com/edouard-lopez/tmux-tomorrow/tree/master
set -g default-terminal "screen-256color"
source-file ~/.tmux/themes/tomorrow.tmux




