:PROPERTIES:
:ID:       7DC487DC-0AA2-4BB2-A54C-9163443A02AC
:ROAM_REFS: cite:wukich-2016-correl-sf
:mtime:    20220227123239
:ctime:    20220227123206
:END:
#+title: Correlation of sf-36 and sf-12 component scores in patients with diabetic foot disease
* ABSTRACT (pubmed)
The assessment of patient outcomes is becoming increasingly
important in all areas of medicine, including foot and ankle
surgery. The Medical Outcomes Study Short Form 36-item
(SF-36) is widely used as a generic measure of quality of
life; however, patients often find answering 36 questions
cumbersome. Consequently, the Short Form 12 (SF-12) was
developed. We hypothesized that the agreement between the
SF-12 and SF-36 component scores would be substantial in
patients with diabetic foot disease. We retrospectively
reviewed the data from 300 patients with diabetes mellitus
(DM) and foot and ankle pathology who completed the SF-36
questionnaire. Of the 300 patients, 155 (51.7%) had problems
directly related to complications of DM and 145 (48.3%) had
routine foot complaints that were unrelated to complications
of DM. The 12 questions of the SF-12 were abstracted from
the SF-36. The overall median score for the SF-36 physical
component summary was 34.70 compared with the overall SF-12
physical component summary of 36.75 (p = .04). The
intraclass correlation coefficient was 0.93688. The overall
median score for the SF-36 mental component summary was
52.40 compared with the overall SF-12 mental component
summary of 51.25 (p = .34). The intraclass correlation
coefficient was 0.95449. Substantial agreement was observed
when comparing the component scores of the SF-12 and the
SF-36. From our study results of 300 patients with DM, it
appears that the SF-36 and SF-12 are comparable outcome
instruments for use with patients with diabetic foot
disease.


