name: Bootstrap

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  bootstrap:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        ls -lah
        pwd
        cd ~ && pwd
        cd ~ && ls -lah
    - run: |
        cd ~ && \
          chmod +x $GITHUB_WORKSPACE/.files/bootstrap.sh && \
          $GITHUB_WORKSPACE/.files/bootstrap.sh
